name: First CI

on: 
  push:
    branches:
      - master

jobs:
  build: 
    runs-on: windows-2019
    steps:
      - name: "checkout"
        uses: actions/checkout@master
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Restore packages
        uses: nuget Restore /Users/himanisharma/Downloads/ProjectTracker/ProjectTrackerApp.sln
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Build with MSBuild
        run: msbuild ProjectTrackerApp.sln -p:Configuration=Release




